[build]
  command = "echo 'Streamlit app - Use Render or Heroku for deployment'"
  publish = "."

[build.environment]
  PYTHON_VERSION = "3.9"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
